server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #    url: jdbc:mysql:///
    username: root
    password: 123456
    #redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
#  连接redis高可用集群
#  redis:
#    sentinel:
#      master: 127.0.0.1
#      nodes: 127.0.0.2:26379,127.0.0.3:26379,127.0.0.4:26379
  cache:
    type: redis
    cache-names: realTimeCache
# 开发阶段，建议关闭thymeleaf缓存，否则可能会出现数据未更新情况
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
student:
  name: "啊哈哈哈哈"
  age: 15
  score: 55.6
group:
  students[0]:
    name: "一"
    age: 15
    score: 99.5
  students[1]:
    name: "二"
    age: 55
    score: 88
#logging:
#  level: debug
