server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

student:
  name: "啊哈哈哈哈"
  age: 15
  score: 55.6
group:
  students[0]:
    name: "一"
    age: 15
    score: 99.5
  students[1]:
    name: "二"
    age: 55
    score: 88